services:
  desktop: # Nom du premier service
    build: 
      context: ./services/Desktop
    container_name: desktop
    restart: unless-stopped
    ports:
      - "80:80" # Mappage des ports
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./services/Desktop:/app # Mappage de volumes
  
  plateforme:
    build:
      context: ./services/plateforme
    container_name: plateforme
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock