services:
  desktop: # Nom du premier service
    build: 
      context: ./services/Desktop
    container_name: desktop
    restart: unless-stopped
    ports:
      - "80:80" # Mappage des ports
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./services/Desktop:/home/nicolasf/app # Mappage de volumes
  
  plateforme:
    build:
      context: ./services/plateforme
      args:
        - USER=root
        - PASSWORD=root 
    container_name: plateforme
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  jenkins:
    build:
      context: ./services/jenkins
    container_name: jenkins
    restart: unless-stopped
    environment:
      - JENKINS_OPTS=--httpPort=80
    ports:
      - "8080:80"
    volumes:
      - jenkins_data:/var/jenkins_home

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - GITEA__server__HTTP_PORT=80
      - GITEA__server__PROTOCOL=http
      - GITEA__server__DOMAIN=gitea
      - GITEA__server__ROOT_URL=http://gitea
      - GITEA__server__LOCAL_ROOT_URL=http://gitea/
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins
    volumes:
      - gitea_data:/data

  jenkins-docker-agent:
    build: 
      context: ./services/jenkins-docker-agent
    privileged: true
    container_name: jenkins-docker-agent
    environment:
      - JENKINS_URL=http://jenkins
      - JENKINS_AGENT_NAME=docker-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=e136834d6d3c7e449a40002b76867894f1e41e45c1f1a8d51cca00d195bcda8d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_data:
  gitea_data: